### ISSUE TITLE
How about Big Sur?

### ISSUE THREAD

**Issue by m0d16l14n1** [ksymmonds/Razer_Blade_Stealth_Late_2019_GTX_Hackintosh#1]
Hello! Did you give a try to boot into BS? Might be graphics gonna work? That`s a pity, that graphics are not working(

**Comment by k-sym** [comment]
Yeah, I did. It complains about needing a firmware update which leads me to believe that the issues may be deeper than I suspected. :/

**Comment by m0d16l14n1** [comment]
What do you mean?

**Comment by k-sym** [comment]
Meaning the installer starts and then it says it can't be installed as the device requires a firmware update. I'm sure it's just a Symbios change that's required, but I just haven't had time to look as yet. :)

**Comment by m0d16l14n1** [comment]
http://bbs.pcbeta.com/viewthread-1868127-1-1.html
http://bbs.pcbeta.com/viewthread-1868124-1-1.html

**Comment by m0d16l14n1** [comment]
they got icelake graphics working + touchpad and audio

**Comment by m0d16l14n1** [comment]
https://github.com/acidanthera/WhateverGreen/pull/62
